AddCSLuaFile( "cl_init.lua" )
AddCSLuaFile("shared.lua")
include('shared.lua')
include('entities/sentinel_base/init.lua')
local vFireExists = file.Exists("lua/autorun/fire_game_modifications.lua","GAME")